Update 4 files
- /matlab/mpm_input_r2023b.txt
- /matlab/license.lic
- /matlab/libmwlmgrimpl.dll
- /matlab/Dockerfile

diff --git a/matlab/Dockerfile b/matlab/Dockerfile
--- a/matlab/Dockerfile
+++ b/matlab/Dockerfile
@@ -1,12 +1,29 @@
-# Copyright 2023 The MathWorks, Inc.
+# Copyright 2019 - 2023 The MathWorks, Inc.
+# This Dockerfile allows you to build a Docker® image with MATLAB® installed using the MATLAB Package 
+# Manager. Use the optional build arguments to customize the version of MATLAB, list of products to 
+# install, and the location at which to install MATLAB.
+
+# Specify license server information using the format: port@hostname 
+ARG LICENSE_SERVER
+
+# The following environment variables allow MathWorks to understand how this MathWorks 
+# product (MATLAB Dockerfile) is being used. This information helps us make MATLAB even better. 
+# Your content, and information about the content within your files, is not shared with MathWorks. 
+# To opt out of this service, delete the environment variables defined in the following line. 
+# To learn more, see the Help Make MATLAB Even Better section in the accompanying README: 
+# https://github.com/mathworks-ref-arch/matlab-dockerfile#help-make-matlab-even-better
+ENV MW_DDUX_FORCE_ENABLE=true MW_CONTEXT_TAGS=MATLAB:DOCKERFILE:V1
+
 FROM eoelab.org:1032/build-image-stacks/jupyter-image-stacks/jupyter:up-c
 LABEL maintainer="Pd.ch <cpd233@outlook.com>"
 
 SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 
-COPY dep.txt /tmp/dep.txt
-
 USER root
+
+WORKDIR /tmp
+
+COPY dep.txt /tmp/dep.txt
 
 
 # base deps,copy by mathworks-ref-arch/container-images
@@ -21,6 +38,30 @@ RUN apt-get update && apt-get install --no-install-recommends -y `cat /tmp/dep.t
 # resolve any license manager issues
     ln -s /lib64/ld-linux-x86-64.so.2 /lib64/ld-lsb-x86-64.so.3 && \
     apt-get clean && rm -rf /var/lib/apt/lists/* 
+
+# Run mpm to install MATLAB in the target location and delete the mpm installation afterwards.
+# If mpm fails to install successfully, then print the logfile in the terminal, otherwise clean up.
+RUN wget -q https://www.mathworks.com/mpm/glnxa64/mpm && chmod +x mpm && \
+    ./mpm install \
+    --release=r2023b \
+    --destination=/opt/matlab/r2023b \
+    --products MATLAB || (echo "MPM Installation Failure. See below for more information:" && cat /tmp/mathworks_root.log && false) && \
+    rm -f mpm /tmp/mathworks_root.log && \
+    && ln -s /opt/matlab/r2023b/bin/matlab /usr/local/bin/matlab
+
+# Alternatively, you can put a license file into the container. Enter the details of the license server in this file and uncomment the following line.
+COPY license.lic /opt/matlab/r2023b/licenses/
+
+COPY libmwlmgrimpl.dll /opt/matlab/r2023b/bin/matlab_startup_plugins/lmgrimpl/
+
+# install matlab kernel
+
+ENV MATLAB_EXECUTABLE=/opt/matlab/r2023b/bin/matlab
+
+RUN pip install pymatbridge && \
+    pip install matlab_kernel && \
+    python -m matlab_kernel install && \
+    cd /opt/matlab/r2023b/extern/engines/python && python setup.py install
 
 USER ${NB_UID}
 WORKDIR "${HOME}"
